Day04/DjangoProject/App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^hello/', views.HelloListView.as_view()),
    url(r"^books/(?P<pk>\d+)", views.BookDetailView.as_view(), name='book_detail'),
]

Day04/DjangoProject/DjangoProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('App.urls', namespace='app')),
]

Day04/DjangoProject/App/models.py
from django.db import models


class Book(models.Model):
    b_name = models.CharField(max_length=64)

Day04/DjangoProject/App/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from App.models import Book


class HelloListView(ListView):

    template_name = 'hello_list.html'

    queryset = Book.objects.all()


class BookDetailView(DetailView):

    template_name = 'book_detail.html'

    queryset = Book.objects.all()

Day04/DjangoProject/templates/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>



<h2>书名:{{ object.b_name }}</h2>


</body>
</html>

Day04/DjangoProject/templates/hello_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<ul>
    {% for book in object_list %}
        <li><a href="{% url 'app:book_detail' pk=book.id %}">{{ book.b_name }}</a></li>
    {% endfor %}
</ul>


</body>
</html>